server:
  port: 1098

spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
  security:
    user:
      name: disabled
      password: disabled
      roles: []

# 日志查看器配置
logs:
  viewer:
    endpoint: /logs
    enable-auth: false
    secret-key:
    paths:
      - C:/Users/root/Desktop/logs
      - C:/Users/root/Documents/项目/github/logs/test-logs/